name: Main Workflow

on:
  push:
    branches: [ master ]


jobs:
  pull:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Copy credentials.json
        run: sudo cp /var/www/credentials.json ${{ github.workspace }}
        
